version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-stretch-node
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: branch name
          command: git branch

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - release
